packages:
  - packages/sdk
  - packages/cli
  - packages/helper
  - packages/infra
  - packages/api-server
  - packages/install-aws
  - packages/ui
  - packages/appliance.sh
  - packages/ui
  - packages/app
  - packages/console
  - packages/desktop
  - packages/bootstrap

onlyBuiltDependencies:
  - '@pulumi/aws-native'
  - '@pulumi/docker'
  - '@pulumi/docker-build'
  - '@swc/core'
  - esbuild
  - nx
  - protobufjs
